# Generated by Django 6.0.7 on 2026-07-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_jobpost_profile_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
