# Generated by Django 6.0.7 on 2026-07-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_profile_about_profile_company_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_document_type',
            field=models.CharField(blank=True, help_text='Trade license, company registration, tax certificate, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recruiter_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
