# Generated by Django 6.0.7 on 2026-07-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_profile_company_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recruiter_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
